added support for toSquare math operation
nickovchinnikov/react-js-tutorial pull request #72
Opened 2020-10-12 19:16 UTC by web2ls

2020-10-13 07:10 UTC, nickovchinnikov commented on src/lesson2/engine.ts
> +export const singleOperandCalc = (stack: ParsedLineType): ParsedLineType => {
Сюда не должен попадать стек, архитектурно это уровень элементарных математических операций

2020-10-13 07:13 UTC, nickovchinnikov commented on src/lesson2/mathOperators.ts
> +export const toSquare: SingleOperandType = (operand: number): number =>
Стоит переиспользовать `pow`

```typescript

export const toSquare: SingleOperandType = (operand: number): number => pow(operand, 2)

2020-10-13 07:14 UTC, nickovchinnikov commented on src/lesson2/mathOperators.ts
> +  "**": FIRST,
Порядок сортировки нарушен

2020-10-13 07:18 UTC, nickovchinnikov commented on tsconfig.json
> +	"compilerOptions": {
Зачем изменены отступы?

2020-10-13 07:20 UTC, nickovchinnikov requested changes
Как стоит сделать, убрав почти все доработки.
По такому же принципу работает операция факториал, подебажить стоит.

Выставить операции `zero`, далее смапить в `scalarOperators` символ с нужным обработчиком.
Добавить на новый обработчик тест-кейсы в mathOperators.test, parser.test, runner.test, engine.test

Профит!

Прежде чем делать каки то доработки, нужно хорошо разобраться в архитектуре решения. Можно понять, как работает инструмент и очень красиво вписать свое решение, а можно внести много доработок, пойдя в обход существующему решению.
Надеюсь вы понимаете, насколько быстро в таком случае программный код выходит из под контроля )

2020-10-13 07:22 UTC, nickovchinnikov commented on src/lesson2/mathOperators.ts
> +export const singleOperandMathOperators: {
Не стоит вводить еще один тип операций, обратите внимание на факториал

2020-10-13 07:23 UTC, nickovchinnikov commented on src/lesson2/parser.test.ts
> +  it("8** + 6", () => {
Не думаю, что факториал так обрабатывает строки. Вы нарушаете всю механику работы стека, внося подобные правки

2020-10-13 07:23 UTC, nickovchinnikov commented on src/lesson2/parser.ts
> +export function checkSingleOperator(item: string): boolean {
Парсер хорошо настроен в текущих условиях, для добавления новой операции (операций) правки тут не требуются

2020-10-13 07:24 UTC, nickovchinnikov commented on src/lesson2/runner.ts
> +import {
Тоже самое, что с парсером

2020-10-13 08:17 UTC, vvscode commented on src/lesson2/mathOperators.ts
> +export const toSquare: SingleOperandType = (operand: number): number =>
а еще указание типов избыточно `SingleOperandType` и описывает `(x: number): number`

2020-10-14 18:13 UTC, vvscode commented on src/lesson2/engine.ts
> +export const singleOperandCalc = (stack: ParsedLineType): ParsedLineType => {
нам явно не хватает тесто на этот кусок кода

сделать `npm run test -- --coverage` и посмотри какие кейсы не покрыты

2020-10-15 10:19 UTC, web2ls commented on tsconfig.json
> +	"compilerOptions": {
тут было добавлено свойство downlevelIteration, отступы не менялись

2020-10-15 10:25 UTC, web2ls commented on src/lesson2/parser.ts
> +export function checkSingleOperator(item: string): boolean {
на примере операции возведения в квадрат: если мы указываем значение, как 8 ** + 6 то парсер в текущем виде пропустит 8 и "**", но забракует "+", так как перед ним не идет число

2020-10-15 10:39 UTC, nickovchinnikov commented on tsconfig.json
> +	"compilerOptions": {
В диффе отступы изменены, посмотрите внимательно

2020-10-15 10:40 UTC, nickovchinnikov commented on src/lesson2/parser.ts
> +export function checkSingleOperator(item: string): boolean {
Пример - операция факториал, думаю сперва вам нужно разобраться с этим примером

2020-10-15 11:05 UTC, web2ls commented on src/lesson2/parser.ts
> +export function checkSingleOperator(item: string): boolean {
факториал это ведь такая же унарная операция и если я запишу 8 ! + 6 или 8! + 6, то у меня все равно вопрос, как парсер это пропустит дальше

2020-10-15 11:09 UTC, nickovchinnikov commented on src/lesson2/parser.ts
> +export function checkSingleOperator(item: string): boolean {
Простите, вы запускали калькулятор? Пробовали разбираться в том, как он работает?

![image](https://user-images.githubusercontent.com/7540752/96115582-d9dc5400-0eef-11eb-9dbc-655cfc59c820.png)

Мне кажется, вам надо прочитать внимательно вот это
https://github.com/nickovchinnikov/react-js-tutorial/pull/72#pullrequestreview-507135328

2020-10-15 12:31 UTC, web2ls commented on src/lesson2/parser.ts
> +export function checkSingleOperator(item: string): boolean {
Если мы говорим про готовое решение калькулятора, то я его не запускал) пытаюсь сделать своими силами на основе базового шаблона)
про введение нулевого приоритета подсказка понятна)
но так как первым встречает строку парсер и он падает с ошибкой  Unexpected string, то пытаюсь понять, что не так

2020-10-15 12:48 UTC, nickovchinnikov commented on src/lesson2/parser.ts
> +export function checkSingleOperator(item: string): boolean {
Простите, не понимаю как можно модифицировать код, не поняв как он работает
Подумайте и продолжайте работу в своём репозитории. Удачи.

2020-10-15 12:48 UTC, closed without merging